# Generated by Django 4.2 on 2023-04-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
    ]
